name: Create Releasable Package Drop

on:
  push:
    branches:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use node version 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Remove existing TypeScript
      run: |
        npm uninstall typescript --no-save
        npm uninstall tslint --no-save
    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
    - name: Adding playwright
      run: npm install --no-save --no-package-lock playwright    
    - name: Validate the browser can import TypeScript
      run: gulp test-browser-integration
    - name: LKG, clean, and pack
      run: |
        gulp LKG
        gulp clean
        npm pack ./
        mv typescript-*.tgz typescript.tgz
      env:
        CI: true
    - name: Upload built tarfile
      uses: actions/upload-artifact@v1
      with:
        name: tgz
        path: typescript.tgz
